# -*- coding: utf-8 -*-
"""Criando um alerta com notification.notify().ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uHUJKEmGllfZaIgs-DeUdKU-LXTn476Y
"""

import plyer

from plyer import notification
import datetime

def alerta(nivel, base, etapa):
    if nivel == 1:
        titulo = "Alerta baixa"
    elif nivel == 2:
        titulo = "Alerta média"
    elif nivel == 3:
        titulo = "Alerta alta"
    else:
        raise ValueError("O nível deve ser 1, 2 ou 3")

    data_atual = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    mensagem = f"Erro ao carregar a base {base} na etapa {etapa}\nData: {data_atual}"

    notification.notify(
        title=titulo,
        message=mensagem,
        app_name='Nome do aplicativo',
        timeout=10
    )

# Chama a função 'alerta' para exibir uma notificação diretamente
try:
    alerta(2, 'Base de dados', 'Etapa 1')
except ValueError as e:
    print(e)